name: meta-mono CI

on:
  push:
    branches:
      - master
      - master-next
  pull_request:
    branches:
      - master
#  release:
#    types: published

jobs:
  meta-mono-build:
    runs-on: [self-hosted, linux]
    environment: 
      name: build
    steps:
    - name: Set environment for branch
      run: |
        if [[ $GITHUB_REF == 'refs/heads/master' ]]; then
          echo "BUILD_TYPE=master" >> "$GITHUB_ENV"
        fi
        if [[ $GITHUB_REF == 'refs/heads/hardknott' ]]; then
          echo "BUILD_TYPE=hardknott" >> "$GITHUB_ENV"
        fi
    - name: Checkout meta-mono
      uses: actions/checkout@v1
    - name: Relocate meta-mono
      run: |
        mkdir ../meta-mono.new
        mkdir ../meta-mono.new/meta-mono
        mv * ../meta-mono.new/meta-mono
        cd ..
        rm -Rf meta-mono
        mv meta-mono.new meta-mono
