name: meta-mono CI

on:
  push:
    branches:
      - master
      - master-next
      - sumo
      - thud
      - warrior
      - zeus
      - dunfell
      - gatesgarth
      - hardknott
      - honister
      - kirkstone
  pull_request:

jobs:
  build-and-test:
    runs-on: [self-hosted, linux]
    env:
      name: build
      MONO_VERSION: 6.12.0.154
      ARCH: x86
    steps:
    - name: Checkout meta-mono
      uses: actions/checkout@v2
      with:
        clean: false
    - name: Relocate meta-mono
      run: |
        mkdir -p ../meta-mono.new/${GITHUB_REF##*/}/meta-mono
        mv * ../meta-mono.new/${GITHUB_REF##*/}/meta-mono
        cd ..
        rm -Rf meta-mono
        mv meta-mono.new meta-mono
    - name: Update repo poky
      run: |
        if [ ! -d 'poky' ]; then
          git clone git://git.yoctoproject.org/poky -b $GITHUB_REF_NAME ${GITHUB_REF##*/}/poky
        else
          cd ${GITHUB_REF##*/}/poky
          git pull origin $GITHUB_REF_NAME
          cd ../..
        fi
    - name: Update repo meta-openembedded
      run: |
        if [ ! -d 'meta-openembedded' ]; then
          git clone https://github.com/openembedded/meta-openembedded.git -b $GITHUB_REF_NAME ${GITHUB_REF##*/}/meta-openembedded
        else
          cd ${GITHUB_REF##*/}/meta-openembedded
          git pull origin $GITHUB_REF_NAME
          cd ../..
        fi 
    - name: Configuring
      run: |
        . ./${GITHUB_REF##*/}/poky/oe-init-build-env ${GITHUB_REF##*/}/build
        if [[ ! $(grep meta-mono/meta-mono/${GITHUB_REF##*/}/meta-mono conf/bblayers.conf) ]]; then
          echo "BBLAYERS += '$GITHUB_WORKSPACE/${GITHUB_REF##*/}/meta-mono'" >> conf/bblayers.conf
        fi
        if [[ ! $(grep meta-openembedded conf/bblayers.conf) ]]; then
          echo "BBLAYERS += '$GITHUB_WORKSPACE/${GITHUB_REF##*/}/meta-openembedded/meta-oe'" >> conf/bblayers.conf
        fi
        if [[ ! $(grep rm_work conf/local.conf) ]]; then
          echo "INHERIT += ' rm_work '" >> conf/local.conf
        fi
        sed -i 's/#IMAGE_CLASSES += "testimage testsdk"/IMAGE_CLASSES += "testimage "/' conf/local.conf
    - name: Building
      run: |
        . ./${GITHUB_REF##*/}/poky/oe-init-build-env ${GITHUB_REF##*/}/build

        export BB_ENV_EXTRAWHITE='$BB_ENV_EXTRAWHITE PREFERRED_VERSION_mono PREFERRED_VERSION_mono-native'
        export BB_ENV_EXTRAWHITE='$BB_ENV_EXTRAWHITE MACHINE DL_DIR'

        env PREFERRED_VERSION_mono="${MONO_VERSION}" PREFERRED_VERSION_mono-native="${MONO_VERSION}" MACHINE="qemu${ARCH}" DL_DIR="$GITHUB_WORKSPACE/downloads" bitbake test-image-mono
    - name: Testing
      run: |
        . ./${GITHUB_REF##*/}/poky/oe-init-build-env ${GITHUB_REF##*/}/build

        export BB_ENV_EXTRAWHITE='$BB_ENV_EXTRAWHITE PREFERRED_VERSION_mono PREFERRED_VERSION_mono-native'
        export BB_ENV_EXTRAWHITE='$BB_ENV_EXTRAWHITE MACHINE DL_DIR'
        export TERM=linux
        env PREFERRED_VERSION_mono="${MONO_VERSION}" PREFERRED_VERSION_mono-native="${MONO_VERSION}" MACHINE="qemu${ARCH}" DL_DIR="$GITHUB_WORKSPACE/downloads" bitbake test-image-mono -c testimage
